packages:
  - app/frontend
  - app/backend

catalog:
  "@vitest/coverage-v8": ^4.0.16
  eslint: ^9.39.2
  prettier: ^3.5.3
  typescript: ^5.7.2
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16

ignoredBuiltDependencies:
  - argon2
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - "@prisma/engines"
  - better-sqlite3
  - prisma
